In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4,5]
l
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
arr1 = np.array([[1,2,3] , [2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
mat = np.matrix(l)

In [ ]:
mat


matrix([[1, 2, 3, 4, 5]])

In [ ]:
np.array(mat)

array([[1, 2, 3, 4, 5]])

In [ ]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [ ]:
np.asarray(mat)

array([[1, 2, 3, 4, 5]])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
a = arr

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr[0] = 100

In [ ]:
a

array([100,   2,   3,   4,   5])

In [ ]:
b = a.copy()

In [ ]:
b

array([100,   2,   3,   4,   5])

In [ ]:
b[0] = 234

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
l

[1, 2, 3, 4, 5]

In [ ]:
[i*i for i in  l]

[1, 4, 9, 16, 25]

In [ ]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('22 23 24',sep = ' ')


array([22., 23., 24.])

In [ ]:
np.fromstring('22 23 24',sep = ' ,')


/tmp/ipython-input-34-251954417.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('22 23 24',sep = ' ,')


array([22.])

In [ ]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr.size

5

In [ ]:
arr1.size

6

In [ ]:
arr.shape

(5,)

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(np.arange(0.4,10.4))

[np.float64(0.4),
 np.float64(1.4),
 np.float64(2.4),
 np.float64(3.3999999999999995),
 np.float64(4.3999999999999995),
 np.float64(5.3999999999999995),
 np.float64(6.3999999999999995),
 np.float64(7.3999999999999995),
 np.float64(8.399999999999999),
 np.float64(9.399999999999999)]

In [ ]:
list(np.arange(.4 , 10.4 , 0.2))

[np.float64(0.4),
 np.float64(0.6000000000000001),
 np.float64(0.8000000000000002),
 np.float64(1.0000000000000002),
 np.float64(1.2000000000000002),
 np.float64(1.4000000000000004),
 np.float64(1.6000000000000005),
 np.float64(1.8000000000000003),
 np.float64(2.0000000000000004),
 np.float64(2.2000000000000006),
 np.float64(2.400000000000001),
 np.float64(2.6000000000000005),
 np.float64(2.8000000000000007),
 np.float64(3.000000000000001),
 np.float64(3.2000000000000006),
 np.float64(3.400000000000001),
 np.float64(3.600000000000001),
 np.float64(3.800000000000001),
 np.float64(4.000000000000002),
 np.float64(4.200000000000001),
 np.float64(4.400000000000002),
 np.float64(4.600000000000001),
 np.float64(4.800000000000002),
 np.float64(5.000000000000002),
 np.float64(5.200000000000002),
 np.float64(5.400000000000002),
 np.float64(5.600000000000002),
 np.float64(5.8000000000000025),
 np.float64(6.000000000000002),
 np.float64(6.200000000000002),
 np.float64(6.400000000000002),
 np.float

In [ ]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [ ]:
np.random.rand(3,4)

array([[0.16118361, 0.57779715, 0.97158718, 0.51491602],
       [0.52199011, 0.59127973, 0.46555281, 0.38139984],
       [0.06736698, 0.27082462, 0.73793343, 0.90271831]])

In [ ]:
arr2 = np.random.randint(1,5 , (3,4))
arr2

array([[4, 2, 3, 4],
       [4, 2, 2, 2],
       [1, 2, 1, 2]])

In [ ]:
arr2.size

12

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.reshape(6,2)

array([[4, 2],
       [3, 4],
       [4, 2],
       [2, 2],
       [1, 2],
       [1, 2]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr2.reshape(2,6)

array([[4, 2, 3, 4, 4, 2],
       [2, 2, 1, 2, 1, 2]])

In [ ]:
arr2.reshape(4,3)

array([[4, 2, 3],
       [4, 4, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr2.reshape(4,-1)

array([[4, 2, 3],
       [4, 4, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr2.reshape(4,-1432453453)

array([[4, 2, 3],
       [4, 4, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [ ]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[2]]],


         [[[3]]]],



        [[[[4]]],


         [[[4]]],


         [[[2]]]]],




       [[[[[2]]],


         [[[2]]],


         [[[1]]]],



        [[[[2]]],


         [[[1]]],


         [[[2]]]]]])

In [ ]:
arr2.reshape(4,-1432453453)
arr2.size

12

In [ ]:
arr1 = np.random.randint(1,10 , (5,6))

In [ ]:
arr1

array([[6, 8, 9, 3, 9, 4],
       [9, 7, 2, 9, 7, 9],
       [7, 2, 2, 6, 5, 6],
       [7, 4, 9, 5, 9, 1],
       [5, 4, 7, 4, 8, 8]])

In [ ]:
arr1 >8

array([[False, False,  True, False,  True, False],
       [ True, False, False,  True, False,  True],
       [False, False, False, False, False, False],
       [False, False,  True, False,  True, False],
       [False, False, False, False, False, False]])

In [ ]:
arr1[arr1 >8]

array([9, 9, 9, 9, 9, 9, 9])

In [ ]:
arr1[0,[0,1]]

array([6, 8])

In [ ]:
arr1[2:4 , [2,3]]

array([[2, 6],
       [9, 5]])

In [ ]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [ ]:
arr1+arr2

array([[3, 2, 4],
       [3, 3, 2],
       [3, 3, 3]])

In [ ]:
arr1*arr2

array([[2, 1, 4],
       [2, 2, 1],
       [2, 2, 2]])

In [ ]:
arr1@arr2

array([[8, 5, 7],
       [6, 4, 5],
       [8, 6, 6]])

In [ ]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [0.5, 0.5, 1. ],
       [0.5, 2. , 0.5]])

In [ ]:
arr1/0

/tmp/ipython-input-86-1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Numpy – Broadcasting.

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([[3,4,5]])

In [ ]:
b

array([[3, 4, 5]])

In [ ]:
arr1 = arr+b.T

In [ ]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [ ]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [ ]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [ ]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [ ]:
np.min(arr1)

np.float64(3.0)

In [ ]:
np.max(arr1)

np.float64(5.0)

In [ ]:
arr = np.random.randint(1,10 , (4,4))

In [ ]:
arr

array([[8, 9, 3, 8],
       [7, 4, 9, 7],
       [3, 3, 1, 1],
       [9, 3, 6, 1]])

In [ ]:
arr.reshape(8,2)

array([[8, 9],
       [3, 8],
       [7, 4],
       [9, 7],
       [3, 3],
       [1, 1],
       [9, 3],
       [6, 1]])

In [ ]:
arr

array([[8, 9, 3, 8],
       [7, 4, 9, 7],
       [3, 3, 1, 1],
       [9, 3, 6, 1]])

In [ ]:
arr.T

array([[8, 7, 3, 9],
       [9, 4, 3, 3],
       [3, 9, 1, 6],
       [8, 7, 1, 1]])

In [ ]:
arr.flatten()

array([8, 9, 3, 8, 7, 4, 9, 7, 3, 3, 1, 1, 9, 3, 6, 1])

In [ ]:
arr

array([[8, 9, 3, 8],
       [7, 4, 9, 7],
       [3, 3, 1, 1],
       [9, 3, 6, 1]])

In [ ]:
np.expand_dims(arr, axis = 1)

array([[[8, 9, 3, 8]],

       [[7, 4, 9, 7]],

       [[3, 3, 1, 1]],

       [[9, 3, 6, 1]]])

In [ ]:
np.expand_dims(arr,axis=0)

array([[[8, 9, 3, 8],
        [7, 4, 9, 7],
        [3, 3, 1, 1],
        [9, 3, 6, 1]]])

In [ ]:
data = np.array([[1] , [2] , [3]])

In [ ]:
np.squeeze(data)

array([1, 2, 3])

In [ ]:
np.repeat(data,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [ ]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Numpy - Binary Operators
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))


In [ ]:
arr1

array([[2, 5, 4, 7],
       [3, 9, 8, 1],
       [1, 9, 1, 4]])

In [ ]:
arr2

array([[5, 8, 4, 1],
       [2, 3, 2, 1],
       [6, 7, 1, 3]])

In [ ]:
arr1 + arr2

array([[ 7, 13,  8,  8],
       [ 5, 12, 10,  2],
       [ 7, 16,  2,  7]])

In [ ]:
arr1*arr2

array([[10, 40, 16,  7],
       [ 6, 27, 16,  1],
       [ 6, 63,  1, 12]])

In [ ]:
arr1/arr2

array([[0.4       , 0.625     , 1.        , 7.        ],
       [1.5       , 3.        , 4.        , 1.        ],
       [0.16666667, 1.28571429, 1.        , 1.33333333]])

In [ ]:
arr1-arr2

array([[-3, -3,  0,  6],
       [ 1,  6,  6,  0],
       [-5,  2,  0,  1]])

In [ ]:
arr1**arr2

array([[     32,  390625,     256,       7],
       [      9,     729,      64,       1],
       [      1, 4782969,       1,      64]])

In [ ]:
~arr1

array([[ -3,  -6,  -5,  -8],
       [ -4, -10,  -9,  -2],
       [ -2, -10,  -2,  -5]])

In [ ]:
arr1

array([[2, 5, 4, 7],
       [3, 9, 8, 1],
       [1, 9, 1, 4]])

In [ ]:
arr1>arr2

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [False,  True, False,  True]])

In [ ]:
#Numpy - String Functions.

In [ ]:
arr = np.array(["sudh" , "kumar"])

In [ ]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [ ]:

np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [ ]:
np.char.lower(arr)

array(['sudh', 'kumar'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [ ]:
#Numpy - Mathematical Functions.

In [ ]:
arr1



array([[2, 5, 4, 7],
       [3, 9, 8, 1],
       [1, 9, 1, 4]])

In [ ]:
np.sin(arr1)

array([[ 0.90929743, -0.95892427, -0.7568025 ,  0.6569866 ],
       [ 0.14112001,  0.41211849,  0.98935825,  0.84147098],
       [ 0.84147098,  0.41211849,  0.84147098, -0.7568025 ]])

In [ ]:
np.cos(arr1)

array([[-0.41614684,  0.28366219, -0.65364362,  0.75390225],
       [-0.9899925 , -0.91113026, -0.14550003,  0.54030231],
       [ 0.54030231, -0.91113026,  0.54030231, -0.65364362]])

In [ ]:
np.tan(arr1)

array([[-2.18503986, -3.38051501,  1.15782128,  0.87144798],
       [-0.14254654, -0.45231566, -6.79971146,  1.55740772],
       [ 1.55740772, -0.45231566,  1.55740772,  1.15782128]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.69897   , 0.60205999, 0.84509804],
       [0.47712125, 0.95424251, 0.90308999, 0.        ],
       [0.        , 0.95424251, 0.        , 0.60205999]])

In [ ]:
np.power(arr1,2)

array([[ 4, 25, 16, 49],
       [ 9, 81, 64,  1],
       [ 1, 81,  1, 16]])

In [ ]:
np.mean(arr1)

np.float64(4.5)

In [ ]:
np.median(arr1)

np.float64(4.0)

In [ ]:
np.std(arr1)

np.float64(2.958039891549808)

In [ ]:
np.var(arr1)

np.float64(8.75)

In [ ]:
np.min(arr1)

np.int64(1)

In [ ]:
np.max(arr1)

np.int64(9)

In [ ]:
#Numpy - Arithmetic Operations.

In [ ]:
np.subtract(arr1,arr2)


array([[-3, -3,  0,  6],
       [ 1,  6,  6,  0],
       [-5,  2,  0,  1]])

In [ ]:
arr1-arr2

array([[-3, -3,  0,  6],
       [ 1,  6,  6,  0],
       [-5,  2,  0,  1]])

In [ ]:
np.multiply(arr1,arr2)

array([[10, 40, 16,  7],
       [ 6, 27, 16,  1],
       [ 6, 63,  1, 12]])

In [ ]:
arr1

array([[2, 5, 4, 7],
       [3, 9, 8, 1],
       [1, 9, 1, 4]])

In [ ]:
arr2

array([[5, 8, 4, 1],
       [2, 3, 2, 1],
       [6, 7, 1, 3]])

In [ ]:
np.mod(arr1,arr2)

array([[2, 5, 0, 0],
       [1, 0, 0, 0],
       [1, 2, 0, 1]])

In [ ]:
np.power(arr1,arr2)

array([[     32,  390625,     256,       7],
       [      9,     729,      64,       1],
       [      1, 4782969,       1,      64]])

In [ ]:
np.power(arr1,10)

array([[      1024,    9765625,    1048576,  282475249],
       [     59049, 3486784401, 1073741824,          1],
       [         1, 3486784401,          1,    1048576]])

In [ ]:
#Numpy - Statistical Functions.

In [ ]:
arr1

array([[2, 5, 4, 7],
       [3, 9, 8, 1],
       [1, 9, 1, 4]])

In [ ]:
np.mean(arr1)

np.float64(4.5)

In [ ]:
np.std(arr1)

np.float64(2.958039891549808)

In [ ]:
np.median(arr1)

np.float64(4.0)

In [ ]:
##Sort, Search & Counting Functions.

In [ ]:
arr = np.array([4,2,8,5,3,9,12,56])

In [ ]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [ ]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [ ]:
np.searchsorted(arr,6)

np.int64(5)

In [ ]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [ ]:
np.count_nonzero(arr1)

6

In [ ]:
np.sort(arr1)

array([  0,   0,   0,   0,   6,   6,  65, 234, 324, 645])

In [ ]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [ ]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [ ]:
#Numpy - Byte Swapping.

In [ ]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
arr.byteswap(True
              )

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [ ]:
#Numpy - Copies &Views.

In [ ]:
arr1

array([                   0,  4900197869555810304, -8862521116711714816,
        4683743612465315840,   432345564227567616,   432345564227567616,
                          0,                    0,                    0,
       -1585267068834414592])

In [ ]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [ ]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
a = np.copy(arr1)

In [ ]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
b = arr1.view()

In [ ]:
b = arr1

In [ ]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
b[0] = 234

In [ ]:
arr1lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2]

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [ ]:
lis = [1, 2, 3, "pwskills", 3+5j, True, 1.2]

In [ ]:
lis

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]

In [ ]:
type(lis)

list

In [ ]:
#Numpy stores the data in an array
#An array is a container used to store the data of same data type


In [ ]:
#why numpy
#Computation is fast>> due to array>>>continous memory location
#mathematical computation

In [ ]:
l = [1, 2, 3, 4, 5]

In [ ]:
arr = np.array(l)

In [ ]:
l = [1, 2, 3, 4, 5.1]
arr = np.array(l)

In [ ]:
arr

array([1. , 2. , 3. , 4. , 5.1])

In [ ]:
l = [1, 2, 3, 4, 5.1, "Ajay"]
arr = np.array(l)

In [ ]:
arr

array(['1', '2', '3', '4', '5.1', 'Ajay'], dtype='<U32')

In [ ]:
#arr stores homogenous data

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.ndim

2

In [ ]:
mat = np.matrix([1, 2, 3, 4]) #matrix is a specialised array, 2 dimensional

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
type(mat)

numpy.matrix

In [ ]:
np.matrix([[[1, 2], [3,4], [5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
#more way to convert array
l = [1, 2, 3]
np.asarray(l)

array([1, 2, 3])

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [ ]:

np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [ ]:
mat

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(mat) #Convert the input to an ndarray, but pass ndarray subclasses through.

matrix([[1, 2, 3, 4]])

In [ ]:
t = ([1, 2, 3], [4, 5, 6]) #tuple to array

In [ ]:
t

([1, 2, 3], [4, 5, 6])

In [ ]:
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)

In [ ]:
a = np.fromfunction(lambda i,j : i==j ,(3,4))

In [ ]:
a

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [ ]:
 b = np.fromfunction(lambda i,j : i**j ,(3,4))

In [ ]:
b

array([[1., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 2., 4., 8.]])

In [ ]:
np.fromstring('22 23 24',sep ='')

/tmp/ipython-input-231-4237826590.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('22 23 24',sep ='')


array([2.88760354e-57])

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [ ]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [ ]:
iterable = (i for i in range(5))

In [ ]:
np.fromiter(iterable, int) #Create a new 1-dimensional array from an iterable object.

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('22,23,24', sep = ",")

array([22., 23., 24.])

In [ ]:
#for string character you have  to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
range(10)

range(0, 10)

In [ ]:
#other methods of numpy>> to generate sequnce of nos
np.arange(1, 10, 0.1) #Return evenly spaced values within a given interval.

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
np.linspace(1, 5, 10)#Return evenly spaced numbers over a specified interval.
#give me 10 numbers between 1 and 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])