<a href="https://colab.research.google.com/github/Anuragsingh007-bit/Data-science-with-generativeAi-masters/blob/main/Numpyad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [342]:
import numpy as np

In [343]:
l = [1,2,3,4]

In [344]:
ar = np.array(l)

In [345]:
ar

array([1, 2, 3, 4])

In [346]:
type(ar)

numpy.ndarray

In [347]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [348]:
np.asarray(l)

array([1, 2, 3, 4])

In [349]:
a= [2,3,4]

In [350]:
np.asanyarray(a)

array([2, 3, 4])

In [351]:
b = np.matrix(l)

In [352]:
b

matrix([[1, 2, 3, 4]])

In [353]:
b

matrix([[1, 2, 3, 4]])

In [354]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [355]:
a = np.array(l)

In [356]:
a

array([1, 2, 3, 4])

In [357]:
c = a

In [358]:
c

array([1, 2, 3, 4])

In [359]:
a

array([1, 2, 3, 4])

In [360]:
c[0] = 100

In [361]:
c

array([100,   2,   3,   4])

In [362]:
a

array([100,   2,   3,   4])

In [363]:
d = np.copy(a)

In [364]:
d

array([100,   2,   3,   4])

In [365]:
a

array([100,   2,   3,   4])

In [366]:
a[1] = 400


In [367]:
a

array([100, 400,   3,   4])

In [368]:
d

array([100,   2,   3,   4])

In [369]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [370]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [371]:
iterable = (i*i for i in range(5))

In [372]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [373]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [374]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

In [375]:
#Numpy - Data Types.

In [376]:
l = [2,3,4,5,6]

In [377]:
ar = np.array(l)

In [378]:
ar

array([2, 3, 4, 5, 6])

In [379]:
ar

array([2, 3, 4, 5, 6])

In [380]:
ar.ndim

1

In [381]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [382]:
ar2.ndim

2

In [383]:
ar.size

5

In [384]:
ar2.size

8

In [385]:
ar

array([2, 3, 4, 5, 6])

In [386]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [387]:
ar.shape

(5,)

In [388]:
ar2.shape

(2, 4)

In [389]:
ar.dtype

dtype('int64')

In [390]:
ar2.dtype

dtype('int64')

In [391]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [392]:
ar22.dtype

dtype('float64')

In [393]:
list(range(5))

[0, 1, 2, 3, 4]

In [394]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [395]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [396]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [397]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [398]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [399]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [400]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [401]:
ar4 = np.zeros((3,4,2,3))

In [402]:
ar4.ndim


4

In [403]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [404]:
np.ones(4)

array([1., 1., 1., 1.])

In [405]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [406]:
on =np.ones((2,3,2))

In [407]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [408]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [409]:
on *4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [410]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [411]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [412]:
np.linspace(2,4 , 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [413]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [414]:
arr = np.random.randn(3,4)

In [415]:
import pandas as pd


In [416]:
pd.DataFrame(arr)

0         1         2         3
0 -0.135043 -0.738031  2.625886  2.415994
1  0.033053 -0.629398  0.553696  0.899482
2 -0.152207  0.113471 -1.065972 -0.210900

In [417]:
np.random.rand(3,4)

array([[0.24749416, 0.23934728, 0.34602389, 0.22739344],
       [0.41807949, 0.20509086, 0.35523965, 0.87516727],
       [0.95106784, 0.56922255, 0.07612886, 0.0705989 ]])

In [418]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [419]:
pd.DataFrame(np.random.randint(1,110 , (300,400))).to_csv('test.csv')

In [420]:
arr = np.random.rand(3,4)

In [421]:
arr

array([[0.29261559, 0.23450628, 0.2712116 , 0.34131806],
       [0.09086692, 0.58455876, 0.30479862, 0.00737798],
       [0.43255904, 0.52676991, 0.52558422, 0.61740129]])

In [422]:
arr.reshape(6,-1)

array([[0.29261559, 0.23450628],
       [0.2712116 , 0.34131806],
       [0.09086692, 0.58455876],
       [0.30479862, 0.00737798],
       [0.43255904, 0.52676991],
       [0.52558422, 0.61740129]])

In [423]:
arr1 = arr.reshape(6,-134353553435)

In [424]:
arr1

array([[0.29261559, 0.23450628],
       [0.2712116 , 0.34131806],
       [0.09086692, 0.58455876],
       [0.30479862, 0.00737798],
       [0.43255904, 0.52676991],
       [0.52558422, 0.61740129]])

In [425]:
arr1[1][1]

np.float64(0.3413180632167412)

In [426]:
arr = np.random.randint(1,100 , (5,5))
arr

array([[61, 26, 46, 67,  8],
       [33, 11, 66, 14,  5],
       [45, 16, 84, 56, 95],
       [28, 13, 82, 80, 77],
       [29, 11, 36, 60, 35]])

In [427]:
arr[arr>50]

array([61, 67, 66, 84, 56, 95, 82, 80, 77, 60])

In [428]:
arr

array([[61, 26, 46, 67,  8],
       [33, 11, 66, 14,  5],
       [45, 16, 84, 56, 95],
       [28, 13, 82, 80, 77],
       [29, 11, 36, 60, 35]])

In [429]:
arr[2:4 , [1,2]]

array([[16, 84],
       [13, 82]])

In [430]:
arr[0][0] = 5000

In [431]:
arr

array([[5000,   26,   46,   67,    8],
       [  33,   11,   66,   14,    5],
       [  45,   16,   84,   56,   95],
       [  28,   13,   82,   80,   77],
       [  29,   11,   36,   60,   35]])

In [432]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [433]:
arr1

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [434]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [435]:
arr1+arr2

array([[4, 3, 3],
       [3, 3, 2],
       [4, 2, 3]])

In [436]:
arr1-arr2

array([[ 0, -1, -1],
       [-1, -1,  0],
       [ 0,  0,  1]])

In [437]:
arr1/arr2

array([[1. , 0.5, 0.5],
       [0.5, 0.5, 1. ],
       [1. , 1. , 2. ]])

In [438]:
arr1 * arr2

array([[4, 2, 2],
       [2, 2, 1],
       [4, 1, 2]])

In [439]:
arr1


array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [440]:
arr2

array([[2, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [441]:
arr1@arr2

array([[ 8,  7,  6],
       [ 6,  5,  4],
       [10,  8,  7]])

In [442]:
arr1/0

/tmp/ipython-input-442-1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [443]:
arr1 + 100

array([[102, 101, 101],
       [101, 101, 101],
       [102, 101, 102]])

In [444]:
arr1**2

array([[4, 1, 1],
       [1, 1, 1],
       [4, 1, 4]])

In [445]:
#Numpy – Broadcasting.

In [446]:
arr =np.zeros((4,4))

In [447]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [448]:
row = np.array([1,2,3,4])

In [449]:
row

array([1, 2, 3, 4])

In [450]:
row.shape



(4,)

In [451]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [452]:
row.T

array([1, 2, 3, 4])

In [453]:
col = np.array([[1,2,3,4]])

In [454]:
col

array([[1, 2, 3, 4]])

In [455]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [456]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [457]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [458]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [459]:
col

array([[1, 2, 3, 4]])

In [460]:

arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [461]:
arr1 = np.random.randint(1,4 , (3,4))
arr1

array([[3, 2, 3, 3],
       [3, 1, 3, 2],
       [1, 2, 3, 3]])

In [462]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.        , 1.73205081, 1.41421356],
       [1.        , 1.41421356, 1.73205081, 1.73205081]])

In [463]:
np.exp(arr1)

array([[20.08553692,  7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  2.71828183, 20.08553692,  7.3890561 ],
       [ 2.71828183,  7.3890561 , 20.08553692, 20.08553692]])

In [464]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.        , 0.47712125, 0.30103   ],
       [0.        , 0.30103   , 0.47712125, 0.47712125]])